Allow opening the browser even when verbose mode is disabled
thgh/rollup-plugin-serve pull request #64
Opened 2020-08-18 02:54 UTC by Richienb

// @thgh

2020-08-19 14:01 UTC, thgh requested changes

2020-08-19 14:01 UTC, thgh commented on src/index.js
> -      if (!running) {
This will keep logging and opening new browsers for every change in watch mode, it should only open the browser the first time that a bundle created.

2020-08-19 14:01 UTC, thgh commented on src/index.js
> +        if (options.verbose) {
Verbose should be enabled by default
```suggestion
        if (options.verbose !== false) {
```

2020-08-19 22:54 UTC, Richienb commented on src/index.js
> +        if (options.verbose) {
Fixed!

2020-08-19 22:54 UTC, Richienb commented
@thgh Fixed!

2020-08-26 03:53 UTC, Richienb commented
// @thgh

2020-08-27 23:36 UTC, merged

2020-08-27 23:45 UTC, thgh commented
Thanks! Released in rollup-plugin-serve@1.0.4

2020-08-27 23:52 UTC, thgh commented on src/index.js
> +        if (options.verbose) {
Something went wrong here 😛  
I tweaked it a little, here is the end result: https://github.com/thgh/rollup-plugin-serve/commit/f6474463bbeb938a13457f8ffafe5d59121e7c0e